import { StudyCard } from './study.types';

export const studyCards: StudyCard[] = [

  {
    id: 'study-fauna-01',
    category: 'fauna',
    title: 'Tartaruga-Oliva',
    subtitle: 'Lepidochelys olivacea',
    emoji: '🐢',
    color: '#10B981',
    badge: 'Em Perigo',
    relatedGameId: 'fauna-001',
    facts: [
      { label: 'Status IUCN', value: 'Vulnerável', icon: '⚠️' },
      { label: 'Peso adulto', value: 'até 50 kg', icon: '⚖️' },
      { label: 'Comprimento', value: '60–75 cm', icon: '📏' },
      { label: 'Alimentação', value: 'Medusas, algas, crustáceos', icon: '🍽️' },
      { label: 'Ninhos no CE', value: 'Projeto TAMAR monitora', icon: '🥚' },
      { label: 'Longevidade', value: 'Até 50 anos', icon: '🕰️' },
    ],
    didYouKnow: 'A tartaruga-oliva é a menor das tartarugas marinhas do Brasil, mas realiza a maior desovas em massa do mundo — chamada "arribada" — onde milhares de fêmeas sobem à praia na mesma noite para desovar. O fenômeno acontece principalmente na Índia (Praia de Gahirmatha), mas ocorre em menor escala na costa cearense.',
  },
  {
    id: 'study-fauna-02',
    category: 'fauna',
    title: 'Peixe-Boi Marinho',
    subtitle: 'Trichechus manatus',
    emoji: '🦭',
    color: '#00D4FF',
    badge: 'Criticamente Ameaçado',
    relatedGameId: 'fauna-001',
    facts: [
      { label: 'Status IUCN', value: 'Vulnerável (no Brasil: CR)', icon: '🔴' },
      { label: 'Peso adulto', value: '400–600 kg', icon: '⚖️' },
      { label: 'Comprimento', value: 'até 4 metros', icon: '📏' },
      { label: 'Alimentação', value: 'Fanerógamas marinhas', icon: '🌿' },
      { label: 'Pop. no Brasil', value: '< 500 indivíduos', icon: '📊' },
      { label: 'Habitat no CE', value: 'Estuários e lagoas costeiras', icon: '🏞️' },
    ],
    didYouKnow: 'O peixe-boi marinho é um mamífero que respira ar mas passa toda a vida no mar. No Ceará, o CMA/ICMBio em Acaraú é responsável pela reabilitação e soltura de animais encalhados. Sua principal ameaça é a colisão com embarcações e o emaranhamento em redes de pesca — não a predação natural.',
  },
  {
    id: 'study-fauna-03',
    category: 'fauna',
    title: 'Golfinho-Rotador',
    subtitle: 'Stenella longirostris',
    emoji: '🐬',
    color: '#7C3AED',
    relatedGameId: 'fauna-001',
    facts: [
      { label: 'Status IUCN', value: 'Menor preocupação', icon: '✅' },
      { label: 'Peso adulto', value: '60–80 kg', icon: '⚖️' },
      { label: 'Comprimento', value: '1,7–2,3 metros', icon: '📏' },
      { label: 'Habitat', value: 'Águas tropicais/subtropicais', icon: '🌊' },
      { label: 'Saltos', value: 'até 3m, 7 rotações/salto', icon: '🌀' },
      { label: 'Referência CE', value: 'Costão do Titanzinho (Fortaleza)', icon: '📍' },
    ],
    didYouKnow: 'O golfinho-rotador é famoso por seus espetaculares saltos com rotações em torno do próprio eixo — podem fazer até 7 rotações num único salto. Fernando de Noronha (PE) abriga a maior concentração do mundo, mas grupos são frequentemente vistos ao largo de Fortaleza, especialmente na Praia do Futuro.',
  },
  {
    id: 'study-fauna-04',
    category: 'fauna',
    title: 'Peixe-Leão (Invasor)',
    subtitle: 'Pterois volitans',
    emoji: '🦁',
    color: '#EF4444',
    badge: 'Espécie Invasora',
    relatedGameId: 'fauna-001',
    facts: [
      { label: 'Origem', value: 'Oceano Indo-Pacífico', icon: '🌏' },
      { label: 'Chegada ao CE', value: '~2014 (confirmado)', icon: '📅' },
      { label: 'Reprodução', value: '30.000 ovos/desova', icon: '🥚' },
      { label: 'Veneno', value: '18 espinhos dorsais venenosos', icon: '☠️' },
      { label: 'Impacto', value: 'Reduz biodiversidade em 80%', icon: '📉' },
      { label: 'Predadores nat.', value: 'Nenhum no Atlântico', icon: '❌' },
    ],
    didYouKnow: 'O peixe-leão não tem predadores naturais no Atlântico e pode comer até 50% do próprio peso por dia. Como solução, pescadores cearenses foram treinados para capturá-los manualmente com puçás, e restaurantes de Fortaleza passaram a servir peixe-leão no cardápio como estratégia de controle biológico!',
  },
  {
    id: 'study-fauna-05',
    category: 'fauna',
    title: 'Mola-Mola (Peixe-Lua)',
    subtitle: 'Mola mola',
    emoji: '🫧',
    color: '#00D4FF',
    relatedGameId: 'fauna-001',
    facts: [
      { label: 'Peso máximo', value: '2.300 kg', icon: '⚖️' },
      { label: 'Comprimento', value: 'até 3,3 metros', icon: '📏' },
      { label: 'Tipo', value: 'Maior peixe ósseo do mundo', icon: '🏆' },
      { label: 'Alimentação', value: 'Medusas e plâncton', icon: '🍽️' },
      { label: 'Ovos/ciclo', value: '300 milhões de ovos', icon: '🥚' },
      { label: 'Avistamentos CE', value: 'Plataforma continental', icon: '🔭' },
    ],
    didYouKnow: 'Apesar de pesar mais de 2 toneladas, o Mola mola começa a vida como um ovo minúsculo — cresce mais de 60 milhões de vezes ao longo da vida! Ele frequentemente "toma banho de sol" deitado na superfície do oceano para aquecer o corpo após mergulhar em águas frias, e é avistado ocasionalmente na costa nordestina.',
  },
  {
    id: 'study-fauna-06',
    category: 'fauna',
    title: 'Boto-Cinza',
    subtitle: 'Sotalia guianensis',
    emoji: '🐬',
    color: '#64748B',
    relatedGameId: 'fauna-001',
    facts: [
      { label: 'Status IUCN', value: 'Quase ameaçado', icon: '⚠️' },
      { label: 'Tamanho adulto', value: 'Até 2 metros', icon: '📏' },
      { label: 'Expectativa', value: 'Cerca de 30 anos', icon: '⏳' },
      { label: 'Alimentação', value: 'Peixes (tainhas, sardinhas), lulas', icon: '🐟' },
      { label: 'No Ceará', value: 'Enseada do Mucuripe, Rio Ceará', icon: '📍' },
      { label: 'Curiosidade', value: 'Vive em baías e águas muito rasas', icon: '🌊' },
    ],
    didYouKnow: 'O Boto-Cinza é o mamífero marinho mais frequentemente visto pelos moradores de Fortaleza. Eles costumam caçar em águas muito rasas, muitas vezes a poucos metros da faixa de areia na Enseada do Mucuripe e na Barra do Ceará. Infelizmente, por viverem tão perto da costa urbana, sofrem grandes riscos com a poluição química e enredamento em redes de pesca.',
  },
  {
    id: 'study-fauna-07',
    category: 'fauna',
    title: 'Polvo-Comum',
    subtitle: 'Octopus vulgaris',
    emoji: '🐙',
    color: '#7C3AED',
    relatedGameId: 'fauna-001',
    facts: [
      { label: 'Corações', value: '3 corações (1 sistêmico + 2 branquiais)', icon: '❤️' },
      { label: 'Sangue', value: 'Azul — contém hemocianina (cobre)', icon: '🔵' },
      { label: 'Inteligência', value: 'Usa ferramentas; reconhece faces humanas', icon: '🧠' },
      { label: 'Braços', value: '8 — cada um com cérebro parcial autônomo', icon: '🦑' },
      { label: 'Defesa', value: 'Tinta + mimetismo + autotomia', icon: '🎭' },
      { label: 'Vida', value: '1–2 anos (morre após reprodução)', icon: '⏳' },
    ],
    didYouKnow: 'O polvo possui 3 corações: dois bombeiam sangue pelas brânquias e um bombeia para o resto do corpo. Mas há mais: seus 8 braços têm neurônios próprios — dois terços do sistema nervoso do polvo está nos braços, não no cérebro central. Isso significa que cada braço pode "pensar" e agir de forma semi-independente.',
  },
  {
    id: 'study-fauna-08',
    category: 'fauna',
    title: 'Estrela-do-Mar',
    subtitle: 'Asteroidea (classe)',
    emoji: '⭐',
    color: '#F59E0B',
    relatedGameId: 'fauna-001',
    facts: [
      { label: 'Alimentação', value: 'Expele estômago para fora para digerir', icon: '🍽️' },
      { label: 'Regeneração', value: 'Regenera braços inteiros cortados', icon: '🔄' },
      { label: 'Locomoção', value: 'Pés tubulares com ventosas (sistema hidráulico)', icon: '🚶' },
      { label: 'Olhos', value: 'Fotorreceptores na ponta de cada braço', icon: '👁️' },
      { label: 'No CE', value: 'Encontrada em recifes e praias rochosas', icon: '📍' },
      { label: 'Curiosidade', value: 'Não é peixe — é equinodermo', icon: '🔬' },
    ],
    didYouKnow: 'A estrela-do-mar tem um dos métodos de alimentação mais estranhos do reino animal: ela abre um bivalve forçando as conchas com os braços, depois expele o estômago para dentro da concha e digere a presa externamente. Uma única estrela pode forçar abrir mexilhões com apenas 0,1 mm de abertura — usando seu sistema hidráulico de pés tubulares.',
  },
  {
    id: 'study-fauna-09',
    category: 'fauna',
    title: 'Tubarão-Tigre',
    subtitle: 'Galeocerdo cuvier',
    emoji: '🦈',
    color: '#475569',
    relatedGameId: 'fauna-001',
    facts: [
      { label: 'Nadadeira dorsal', value: 'Estabilização e equilíbrio lateral', icon: '🏊' },
      { label: 'Propulsão', value: 'Nadadeira caudal (cauda)', icon: '💨' },
      { label: 'Comprimento', value: 'até 5,5 m', icon: '📏' },
      { label: 'Dentes', value: 'Serrilhados; troca ao longo da vida', icon: '🦷' },
      { label: 'Sentido', value: 'Detecta campos elétricos (ampolas de Lorenzini)', icon: '⚡' },
      { label: 'No CE', value: 'Avistado ao largo da plataforma continental', icon: '📍' },
    ],
    didYouKnow: 'A nadadeira dorsal do tubarão — símbolo universal de perigo — serve principalmente para estabilização, evitando que o animal role de lado enquanto nada. A propulsão real vem da poderosa cauda. Os tubarões também possuem "ampolas de Lorenzini", receptores que detectam campos elétricos gerados pelo batimento cardíaco das presas, tornando-os caçadores extraordinários mesmo na escuridão total.',
  },
  {
    id: 'study-fauna-10',
    category: 'fauna',
    title: 'Cavalo-Marinho',
    subtitle: 'Hippocampus reidi',
    emoji: '🐴',
    color: '#10B981',
    badge: 'Único no reino animal',
    relatedGameId: 'fauna-001',
    facts: [
      { label: 'Gestação', value: '2 a 4 semanas (no macho!)', icon: '🤰' },
      { label: 'Filhotes/parto', value: '5 a 2.000 filhotes por vez', icon: '👶' },
      { label: 'Locomoção', value: 'Nadadeira dorsal — até 35 bat/segundo', icon: '💨' },
      { label: 'Camuflagem', value: 'Muda de cor em milissegundos', icon: '🎨' },
      { label: 'No CE', value: 'H. reidi em manguezais e recifes', icon: '📍' },
      { label: 'Ameaça', value: 'Medicina tradicional asiática; pesca acidental', icon: '⚠️' },
    ],
    didYouKnow: 'O cavalo-marinho é o único animal no mundo onde o macho engravida de verdade: a fêmea deposita os ovos na bolsa incubadora do macho, que os fertiliza e carrega por 2 a 4 semanas. No parto, contrações musculares expulsam os filhotes — completamente formados e independentes. O cavalo-marinho brasileiro (H. reidi) é encontrado nos manguezais do Ceará.',
  },

  {
    id: 'study-flora-01',
    category: 'flora',
    title: 'Manguezal Cearense',
    subtitle: 'Rhizophora mangle · Avicennia · Laguncularia',
    emoji: '🌳',
    color: '#10B981',
    relatedGameId: 'flora-001',
    facts: [
      { label: 'Área no CE', value: '~25.000 hectares', icon: '🗺️' },
      { label: 'Espécies arbóreas', value: '4 principais no CE', icon: '🌱' },
      { label: 'Carbono capturado', value: '5x florestas tropicais', icon: '🌍' },
      { label: 'Espécies dependentes', value: '> 70% frutos do mar tropicais', icon: '🦐' },
      { label: 'Rios com mangue', value: 'Jaguaribe, Acaraú, Choró', icon: '🏞️' },
      { label: 'Proteção legal', value: 'APP (Lei 12.651/2012)', icon: '⚖️' },
    ],
    didYouKnow: 'Os manguezais do Ceará são "berçários do mar" — praticamente todos os camarões e lagostas que chegam à sua mesa passaram parte da vida num manguezal. Além disso, capturam carbono 5 vezes mais eficientemente que florestas tropicais terrestres, sendo aliados essenciais contra as mudanças climáticas.',
  },
  {
    id: 'study-flora-02',
    category: 'flora',
    title: 'Recifes de Coral',
    subtitle: 'Siderastrea stellata · Montastraea cavernosa',
    emoji: '🪸',
    color: '#F59E0B',
    badge: 'Vulnerável',
    relatedGameId: 'flora-001',
    facts: [
      { label: 'Crescimento', value: '0,3–10 cm por ano', icon: '📏' },
      { label: 'Cobertura global', value: '< 1% do oceano', icon: '📊' },
      { label: 'Biodiversidade', value: '25% das espécies marinhas', icon: '🐠' },
      { label: 'Temperatura ideal', value: '18–29°C', icon: '🌡️' },
      { label: 'Ameaça', value: 'Branqueamento por + 1°C', icon: '⚠️' },
      { label: 'No Ceará', value: 'Recifes de Aracati e Itarema', icon: '📍' },
    ],
    didYouKnow: 'Os corais do Ceará abrigam espécies endêmicas do Atlântico Sul que não existem em nenhum outro lugar do planeta. O branqueamento de corais — quando eles ficam brancos e morrem — ocorre porque o coral expulsa as algas simbiontes (zooxantelas) que lhe dão cor e energia quando a temperatura da água sobe apenas 1°C acima do normal por 8+ semanas.',
  },
  {
    id: 'study-flora-03',
    category: 'flora',
    title: 'Rodolitos / Algas Calcárias',
    subtitle: 'Lithothamnion · Mesophyllum',
    emoji: '🔮',
    color: '#7C3AED',
    badge: 'Descoberta Recente',
    relatedGameId: 'flora-001',
    facts: [
      { label: 'Tipo', value: 'Algas vermelhas calcárias', icon: '🔬' },
      { label: 'Crescimento', value: '0,1–1 mm por ano', icon: '📏' },
      { label: 'Habitat', value: 'Plataforma continental do CE', icon: '🗺️' },
      { label: 'Importância', value: 'Hotspot de biodiversidade', icon: '⭐' },
      { label: 'Ameaça', value: 'Arrasto de pesca, acidificação', icon: '⚠️' },
      { label: 'Reconhecimento', value: 'Patrimônio natural do CE', icon: '🏛️' },
    ],
    didYouKnow: 'Os bancos de rodolitos do Ceará foram descritos pela ciência apenas nos anos 2000 e rapidamente reconhecidos como um dos mais importantes do mundo. Um nódulo de rodolito pode ter centenas de anos — o que parece uma pedra colorida no fundo do mar é na verdade um ser vivo em crescimento extremamente lento.',
  },
  {
    id: 'study-flora-04',
    category: 'flora',
    title: 'Fanerógamas Marinhas',
    subtitle: 'Halodule wrightii · Syringodium filiforme',
    emoji: '🌾',
    color: '#10B981',
    relatedGameId: 'flora-001',
    facts: [
      { label: 'Tipo', value: 'Plantas com flores (não algas!)', icon: '🌸' },
      { label: 'CO₂ capturado', value: '35x florestas terrestres', icon: '🌍' },
      { label: 'Habitat', value: 'Zonas entre-marés do CE', icon: '🏖️' },
      { label: 'Alimento', value: 'Peixe-boi, tartaruga-verde', icon: '🐢' },
      { label: 'Recuperação', value: 'Muito lenta após destruição', icon: '⏳' },
      { label: 'Ameaça', value: 'Âncoras, turbulência de barcos', icon: '⚓' },
    ],
    didYouKnow: '"Gramas do mar" são as plantas mais eficientes do planeta em capturar carbono — chegam a absorver CO₂ 35 vezes mais rápido que florestas tropicais terrestres! São chamadas de "blue carbon" e estão no centro das estratégias de combate às mudanças climáticas. No Ceará, formam pradarias submersas essenciais para tartarugas e peixes juvenis.',
  },
  {
    id: 'study-flora-05',
    category: 'flora',
    title: 'Coral-de-Fogo',
    subtitle: 'Millepora alcicornis',
    emoji: '🔥',
    color: '#EF4444',
    badge: 'Não é coral verdadeiro',
    relatedGameId: 'flora-001',
    facts: [
      { label: 'Classificação', value: 'Hidrozoário (não é coral pétreo)', icon: '🔬' },
      { label: 'Urticância', value: 'Nematocistos causam ardor intenso', icon: '🔥' },
      { label: 'Cor', value: 'Amarelo-mostarda a alaranjado', icon: '🎨' },
      { label: 'Estrutura', value: 'Calcária, forma ramos ou placas', icon: '🏗️' },
      { label: 'No CE', value: 'Comum em recifes rasos (0–15 m)', icon: '📍' },
      { label: 'Simbiontes', value: 'Abriga zooxantelas como corais verdadeiros', icon: '🌿' },
    ],
    didYouKnow: 'O coral-de-fogo (Millepora alcicornis) engana até mergulhadores experientes: parece um coral, cresce como coral e vive onde os corais vivem — mas tecnicamente é um hidrozoário colonial, parente das medusas e das anêmonas. Seu apelido vem da sensação de queimação imediata ao toque, causada por minúsculos nematocistos que disparam substâncias urticantes em milissegundos.',
  },
  {
    id: 'study-flora-06',
    category: 'flora',
    title: 'Caulerpa taxifolia',
    subtitle: 'Macroalga verde invasora',
    emoji: '🌱',
    color: '#EF4444',
    badge: 'Espécie Invasora',
    relatedGameId: 'flora-001',
    facts: [
      { label: 'Tipo', value: 'Macroalga verde (Chlorophyta)', icon: '🔬' },
      { label: 'Origem', value: 'Indo-Pacífico; escapou de aquários', icon: '🌏' },
      { label: 'Crescimento', value: 'Até 8 cm/dia em condições ideais', icon: '📈' },
      { label: 'Toxinas', value: 'Caulerpenina — afasta herbívoros', icon: '☠️' },
      { label: 'Dano', value: 'Sufoca corais e exclui biodiversidade', icon: '⚠️' },
      { label: 'No Brasil', value: 'Monitorada no NE; controle ativo', icon: '🔍' },
    ],
    didYouKnow: 'A Caulerpa taxifolia ficou conhecida como o "assassino do Mediterrâneo": escapou de aquários de Monaco nos anos 1980 e cobriu mais de 130 km² de fundo marinho, destruindo ecossistemas inteiros. A planta produz uma toxina chamada caulerpenina que afasta praticamente todos os herbívoros, tornando impossível controlá-la biologicamente. No Brasil, o monitoramento dos recifes nordestinos é constante para evitar invasão.',
  },
  {
    id: 'study-flora-07',
    category: 'flora',
    title: 'Marés Vermelhas (HABs)',
    subtitle: 'Florações de Algas Nocivas',
    emoji: '🔴',
    color: '#EF4444',
    badge: 'Risco à saúde',
    relatedGameId: 'flora-001',
    facts: [
      { label: 'Causa', value: 'Proliferação de dinoflagelados tóxicos', icon: '🦠' },
      { label: 'Gatilho', value: 'Eutrofização + temperatura elevada', icon: '🌡️' },
      { label: 'Toxinas', value: 'PSP, DSP, NSP — intoxicação em humanos', icon: '☠️' },
      { label: 'Impacto', value: 'Mortandade de peixes e contaminação de mariscos', icon: '🐟' },
      { label: 'No CE', value: 'Episódios registrados no litoral leste', icon: '📍' },
      { label: 'Proibição', value: 'SEMACE proíbe pesca durante eventos', icon: '⛔' },
    ],
    didYouKnow: 'Durante uma maré vermelha, um único marisco pode concentrar toxinas suficientes para matar um humano adulto — mesmo que o marisco pareça saudável e seja cozido. As toxinas de dinoflagelados são termoestáveis (não se destroem no calor). No Ceará, episódios de floração já causaram mortandade de peixes em praias do litoral leste, gerando alertas da SEMACE e proibições temporárias de pesca.',
  },
  {
    id: 'study-flora-08',
    category: 'flora',
    title: 'Pedra da Risca do Meio',
    subtitle: 'Parque Estadual Marinho do Ceará',
    emoji: '🪸',
    color: '#00D4FF',
    badge: 'Oásis Submerso',
    relatedGameId: 'flora-001',
    facts: [
      { label: 'Localização', value: '18 km do Porto do Mucuripe (CE)', icon: '📍' },
      { label: 'Área protegida', value: '4.790 hectares', icon: '🗺️' },
      { label: 'Biodiversidade', value: 'Centenas de peixes, corais e esponjas', icon: '🐠' },
      { label: 'Profundidade', value: '17 a 30 metros', icon: '🌊' },
      { label: 'Atividades', value: 'Mergulho autônomo, pesca artesanal', icon: '🤿' },
      { label: 'Criação', value: 'Criado pela Lei Estadual 12.717/1997', icon: '🏛️' },
    ],
    didYouKnow: 'O Parque Estadual Marinho da Pedra da Risca do Meio (PEMPRM) é a única unidade de conservação totalmente marinha do Ceará. Ele fica a cerca de 1 hora de barco partindo de Fortaleza. Diferente dos recifes que afloram na superfície, ele é um recife "profundo", formado principalmente por algas calcárias, corais e esponjas gigantes, servindo de berçário para a vida marinha.',
  },

  {
    id: 'study-poll-01',
    category: 'pollution',
    title: 'Plástico no Oceano',
    subtitle: 'A crise dos resíduos sólidos marinhos',
    emoji: '🧴',
    color: '#EF4444',
    badge: 'Urgente',
    relatedGameId: 'pollution-001',
    facts: [
      { label: 'Plástico no mar/ano', value: '11 milhões de toneladas', icon: '📊' },
      { label: 'Grande Pacífico de Lixo', value: '1,6 milhão de km²', icon: '🗺️' },
      { label: 'Decomposição copo', value: '450 anos', icon: '⏳' },
      { label: 'Origem terrestre', value: '80% do lixo marinho', icon: '🏙️' },
      { label: 'Microplástico', value: 'Encontrado em sangue humano', icon: '🩸' },
      { label: 'Ceará - Praias', value: '~8t lixo/km de praia/ano', icon: '🏖️' },
    ],
    didYouKnow: 'Em 2022, pesquisadores da Vrije Universiteit Amsterdam encontraram microplásticos no sangue de 77% dos humanos testados. Os microplásticos chegam a nós através dos frutos do mar que consumimos, da água que bebemos e até do ar que respiramos — toda a cadeia alimentar oceânica está contaminada.',
  },
  {
    id: 'study-poll-02',
    category: 'pollution',
    title: 'Poluição em Fortaleza',
    subtitle: 'Diagnóstico das praias urbanas',
    emoji: '🏙️',
    color: '#F59E0B',
    relatedGameId: 'pollution-001',
    facts: [
      { label: 'Esgoto tratado no CE', value: '~40% (2024)', icon: '🚨' },
      { label: 'Praias impróprias', value: '60–70% (verão chuvoso)', icon: '⛔' },
      { label: 'Principal causa', value: 'Ligações irregulares de esgoto', icon: '🔧' },
      { label: 'Responsável', value: 'CAGECE + Prefeitura Fortaleza', icon: '🏛️' },
      { label: 'Monitoramento', value: 'SEMACE (semanal)', icon: '🔬' },
      { label: 'Balneabilidade', value: 'Mucuripe e Serviluz críticas', icon: '📍' },
    ],
    didYouKnow: 'Das 34 praias monitoradas pela SEMACE em Fortaleza, mais da metade são consideradas impróprias para banho durante todo o ano. A principal causa não é o lixo visível, mas o esgoto doméstico in natura que chega ao mar pelas galerias pluviais — o mesmo canal por onde corre a água da chuva nas ruas.',
  },
  {
    id: 'study-poll-03',
    category: 'pollution',
    title: 'Acidificação dos Oceanos',
    subtitle: 'O impacto invisível do CO₂',
    emoji: '⚗️',
    color: '#7C3AED',
    relatedGameId: 'pollution-001',
    facts: [
      { label: 'CO₂ absorvido', value: '30% de todo emitido', icon: '☁️' },
      { label: 'Queda de pH', value: '8,2 → 8,1 (desde 1750)', icon: '📉' },
      { label: 'Aumento acidez', value: '26% mais ácido', icon: '⚗️' },
      { label: 'Impacto em 2100', value: '-0,4 pH previsto', icon: '🔮' },
      { label: 'Afetados', value: 'Corais, moluscos, ostras', icon: '🦪' },
      { label: 'Apelido', value: '"Osteoporose do oceano"', icon: '🦴' },
    ],
    didYouKnow: 'O oceano absorve tanto CO₂ que se tornou 26% mais ácido desde a Revolução Industrial. Parece pouco, mas esse pH mais baixo torna impossível para corais, ostras e outros organismos formarem suas estruturas calcárias — é como se o oceano estivesse "dissolvendo" os esqueletos e conchas desses animais. Por isso chamam de "osteoporose do oceano".',
  },
  {
    id: 'study-poll-04',
    category: 'pollution',
    title: 'O Que Você Pode Fazer',
    subtitle: 'Ações reais de impacto',
    emoji: '💪',
    color: '#10B981',
    relatedGameId: 'pollution-001',
    facts: [
      { label: 'Impacto #1', value: 'Eliminar plástico descartável', icon: '🚫' },
      { label: 'Impacto #2', value: 'Pressionar por políticas públicas', icon: '📣' },
      { label: 'Impacto #3', value: 'Consumir frutos do mar certificados', icon: '✅' },
      { label: 'Impacto #4', value: 'Conscientizar sua rede social', icon: '📱' },
      { label: 'ONG no CE', value: 'Mar Sem Fim, Instituto Cactus', icon: '🤝' },
      { label: 'Participar', value: 'Mutirões de limpeza (mensal em Fortaleza)', icon: '🧹' },
    ],
    didYouKnow: 'Pesquisas mostram que cada pessoa que adota estilo de vida de baixo plástico influencia em média 3 outras pessoas a mudar comportamentos. Universitários são o grupo com maior poder de multiplicação de mudanças culturais — a geração que vai tomar as decisões políticas e empresariais dos próximos 30 anos.',
  },

  {
    id: 'study-eco-01',
    category: 'flora',
    title: 'Caranguejo-Uçá',
    subtitle: 'Ucides cordatus',
    emoji: '🦀',
    color: '#10B981',
    badge: 'Zona de Raízes',
    relatedGameId: 'eco-001',
    relatedGameSlug: 'ecossistema',
    facts: [
      { label: 'Habitat', value: 'Raízes e lama do mangue', icon: '🌿' },
      { label: 'Comprimento', value: 'até 10 cm (carapaça)', icon: '📏' },
      { label: 'Alimentação', value: 'Folhas e detritos do mangue', icon: '🍃' },
      { label: 'Importância', value: 'Aeração do solo + ciclagem de nutrientes', icon: '🔄' },
      { label: 'Pesca no CE', value: 'Principal espécie extrativista', icon: '🎣' },
      { label: 'Risco', value: 'Sobrepesca e destruição do manguezal', icon: '⚠️' },
    ],
    didYouKnow: 'O caranguejo-uçá é o mais importante do manguezal cearense — sustenta comunidades inteiras de pescadores artesanais. Ele escava tocas de até 1 metro de profundidade nas raízes do mangue, aerando o solo e acelerando a decomposição das folhas. Durante a "andada" (período reprodutivo), milhares de caranguejos atravessam estradas causando bloqueios famosos na CE-085.',
  },
  {
    id: 'study-eco-02',
    category: 'flora',
    title: 'Ostra-do-Mangue',
    subtitle: 'Crassostrea rhizophorae',
    emoji: '🦪',
    color: '#10B981',
    badge: 'Zona de Raízes',
    relatedGameId: 'eco-001',
    relatedGameSlug: 'ecossistema',
    facts: [
      { label: 'Habitat', value: 'Raízes submersas do mangue', icon: '🌿' },
      { label: 'Filtração', value: '100–200 L de água/dia', icon: '💧' },
      { label: 'Alimentação', value: 'Fitoplâncton e material em suspensão', icon: '🔬' },
      { label: 'Fixação', value: 'Fixa nas raízes de rizófora', icon: '⚓' },
      { label: 'Cultivo no CE', value: 'Ostreicultura em Fortim e Acaraú', icon: '🏭' },
      { label: 'Qualidade', value: 'Bioindicador ambiental', icon: '📊' },
    ],
    didYouKnow: 'Uma única ostra filtra até 200 litros de água por dia, removendo algas em excesso e partículas em suspensão. Por isso, a presença de ostras saudáveis numa área é sinal de água limpa. No Ceará, projetos de ostreicultura em manguezais geram renda para marisqueiras e ao mesmo tempo restauram a qualidade da água estuarina.',
  },
  {
    id: 'study-eco-03',
    category: 'flora',
    title: 'Guaiamum',
    subtitle: 'Cardisoma guanhumi',
    emoji: '🦞',
    color: '#10B981',
    badge: 'Zona de Raízes',
    relatedGameId: 'eco-001',
    relatedGameSlug: 'ecossistema',
    facts: [
      { label: 'Habitat', value: 'Borda do manguezal, raízes e solo úmido', icon: '🌿' },
      { label: 'Tamanho', value: 'até 15 cm, pesa até 500 g', icon: '⚖️' },
      { label: 'Cor', value: 'Azul-violeta intenso (adultos)', icon: '🎨' },
      { label: 'Tocas', value: 'Até 1,5 m de profundidade', icon: '🕳️' },
      { label: 'Migração', value: 'Vai ao mar para desovar (lua cheia)', icon: '🌕' },
      { label: 'Status', value: 'Pesca regulamentada por IN IBAMA', icon: '⚖️' },
    ],
    didYouKnow: 'O guaiamum é inconfundível pela coloração azul-violeta vibrante. Ele não vive no mar, mas precisa dele: na época reprodutiva (novembro–janeiro), as fêmeas caminham até a beira da água para liberar seus ovos. Esse comportamento o torna vulnerável ao atropelamento em estradas litorâneas durante suas migrações noturnas de lua cheia.',
  },
  {
    id: 'study-eco-04',
    category: 'flora',
    title: 'Garça-Branca-Grande',
    subtitle: 'Ardea alba',
    emoji: '🦢',
    color: '#F59E0B',
    badge: 'Zona Costeira',
    relatedGameId: 'eco-001',
    relatedGameSlug: 'ecossistema',
    facts: [
      { label: 'Habitat', value: 'Margem do manguezal, zonas úmidas', icon: '🏝️' },
      { label: 'Envergadura', value: 'até 170 cm', icon: '📏' },
      { label: 'Alimentação', value: 'Peixes, camarões, rãs, insetos', icon: '🐟' },
      { label: 'Técnica de caça', value: 'Imóvel; espera a presa se aproximar', icon: '🎯' },
      { label: 'Nidificação', value: 'Em colônias nas copas do mangue', icon: '🌳' },
      { label: 'Status', value: 'Pouco preocupante (IUCN)', icon: '✅' },
    ],
    didYouKnow: 'A garça-branca-grande usa uma estratégia de caça fascinante: às vezes abre as asas para criar sombra sobre a água, atraindo peixes que buscam o frescor — comportamento chamado de "canopy feeding". No Ceará, forma grandes colônias de nidificação (garçais) nas copas do manguezal, visíveis ao entardecer em locais como Caucaia e Aquiraz.',
  },
  {
    id: 'study-eco-05',
    category: 'flora',
    title: 'Socó-do-Mangue',
    subtitle: 'Butorides striata',
    emoji: '🐦',
    color: '#F59E0B',
    badge: 'Zona Costeira',
    relatedGameId: 'eco-001',
    relatedGameSlug: 'ecossistema',
    facts: [
      { label: 'Habitat', value: 'Interior e borda do manguezal', icon: '🌿' },
      { label: 'Comprimento', value: '40–48 cm', icon: '📏' },
      { label: 'Alimentação', value: 'Peixes, camarões, insetos aquáticos', icon: '🐟' },
      { label: 'Caça', value: 'Usa iscas! Deposita insetos na água', icon: '🧠' },
      { label: 'Coloração', value: 'Dorso cinza-esverdeado camuflado', icon: '🎨' },
      { label: 'Status', value: 'Pouco preocupante (IUCN)', icon: '✅' },
    ],
    didYouKnow: 'O socó-do-mangue é uma das poucas aves do mundo que usa ferramentas: ele coloca insetos, sementes ou pétalas sobre a água como isca para atrair peixes — comportamento observado no Brasil e registrado em vídeo por pesquisadores da UECE. É considerado um dos pássaros mais inteligentes da avifauna do manguezal cearense.',
  },
  {
    id: 'study-eco-06',
    category: 'flora',
    title: 'Tainha',
    subtitle: 'Mugil liza',
    emoji: '🐟',
    color: '#00D4FF',
    badge: 'Zona Aquática',
    relatedGameId: 'eco-001',
    relatedGameSlug: 'ecossistema',
    facts: [
      { label: 'Habitat', value: 'Estuários, lagoas costeiras, mar aberto', icon: '🌊' },
      { label: 'Comprimento', value: 'até 60 cm', icon: '📏' },
      { label: 'Alimentação', value: 'Detritos orgânicos e algas bentônicas', icon: '🌿' },
      { label: 'Pesca no CE', value: 'Artesanal e industrial (tainha e ovas)', icon: '🎣' },
      { label: 'Migração', value: 'Desce em cardumes para desovar no mar', icon: '🐠' },
      { label: 'Valor econômico', value: 'Alta — ovas (botarga) = produto gourmet', icon: '💰' },
    ],
    didYouKnow: 'A tainha começa sua vida nos estuários e manguezais, usando as águas calmas como berçário, e quando adulta migra para o mar aberto para se reproduzir. As ovas de tainha (chamadas de "botarga" ou "bottarga") são consideradas uma iguaria gourmet no mundo todo — e no Ceará essa tradição está sendo resgatada por cozinheiros e marisqueiras artesanais.',
  },
  {
    id: 'study-eco-07',
    category: 'flora',
    title: 'Siri-Azul',
    subtitle: 'Callinectes sapidus',
    emoji: '🦐',
    color: '#00D4FF',
    badge: 'Zona Aquática',
    relatedGameId: 'eco-001',
    relatedGameSlug: 'ecossistema',
    facts: [
      { label: 'Habitat', value: 'Estuários, baías, plataforma continental', icon: '🌊' },
      { label: 'Largura', value: 'até 23 cm entre espinhos', icon: '📏' },
      { label: 'Alimentação', value: 'Onívoro: moluscos, peixes, detritos', icon: '🍽️' },
      { label: 'Velocidade', value: 'Nada lateralmente, muito ágil', icon: '💨' },
      { label: 'Pesca no CE', value: 'Pratos típicos de frutos do mar', icon: '🦞' },
      { label: 'Reprodução', value: 'Fêmea migra ao mar para liberar larvas', icon: '🌊' },
    ],
    didYouKnow: 'O siri-azul é capaz de regenerar partes do corpo após perder uma pata ou uma quela — o membro cresce de volta na próxima muda. Esse processo de regeneração o torna símbolo de resiliência nos ecossistemas costeiros. No Ceará, a pesca artesanal de siri com "siri-gaiolas" é tradicional em municípios como Fortim e Acaraú.',
  },
  {
    id: 'study-eco-08',
    category: 'flora',
    title: 'Robalo',
    subtitle: 'Centropomus undecimalis',
    emoji: '🐠',
    color: '#00D4FF',
    badge: 'Zona Aquática',
    relatedGameId: 'eco-001',
    relatedGameSlug: 'ecossistema',
    facts: [
      { label: 'Habitat', value: 'Estuários, manguezais, recifes costeiros', icon: '🌊' },
      { label: 'Comprimento', value: 'até 1,4 m', icon: '📏' },
      { label: 'Alimentação', value: 'Peixe predador: tainhas, camarões', icon: '🎯' },
      { label: 'Pesca esportiva', value: 'Um dos mais valorizados do NE', icon: '🏆' },
      { label: 'Linha lateral', value: 'Escura e característica — marca do espécie', icon: '🖊️' },
      { label: 'Reprodução', value: 'Usa estuários como berçário', icon: '🌿' },
    ],
    didYouKnow: 'O robalo é considerado o "rei da pesca esportiva" no Nordeste brasileiro. Ele usa os estuários e manguezais como área de alimentação e berçário, mas se reproduz em mar aberto. Sua linha lateral escura (tão característica que deu origem ao nome "snook" em inglês) serve para detectar vibrações na água com altíssima precisão na caça.',
  },
  {
    id: 'study-eco-09',
    category: 'flora',
    title: 'Camarão-Rosa',
    subtitle: 'Farfantepenaeus brasiliensis',
    emoji: '🦩',
    color: '#00D4FF',
    badge: 'Zona Aquática',
    relatedGameId: 'eco-001',
    relatedGameSlug: 'ecossistema',
    facts: [
      { label: 'Habitat juvenil', value: 'Estuários e manguezais (berçário)', icon: '🌿' },
      { label: 'Habitat adulto', value: 'Plataforma continental (20–60 m)', icon: '🌊' },
      { label: 'Comprimento', value: 'até 19 cm (fêmeas)', icon: '📏' },
      { label: 'Pesca no CE', value: 'Principal espécie da pesca artesanal', icon: '🎣' },
      { label: 'Produção', value: 'CE: maior produtor de camarão do BR', icon: '🏆' },
      { label: 'Ameaça', value: 'Destruição dos manguezais = colapso da pesca', icon: '⚠️' },
    ],
    didYouKnow: 'O camarão-rosa começa sua vida nos manguezais cearenses — sem esses "berçários" não haveria camarão no mar. O Ceará é o maior produtor de camarão do Brasil, mas a destruição de manguezais para criar fazendas de camarão (carcinicultura) acaba com o habitat que torna essa produção possível — uma contradição que ameaça a própria indústria.',
  },
];

export const StudyModel = {
  getAll(): StudyCard[] {
    return studyCards;
  },
  getByCategory(category: string): StudyCard[] {
    return studyCards.filter((c) => c.category === category);
  },
  getById(id: string): StudyCard | undefined {
    return studyCards.find((c) => c.id === id);
  },
  getCategories(): string[] {
    return ['fauna', 'flora', 'pollution'];
  },
};
